version: '3.3'
services:
  fl_server:
    container_name: federation-lab-server
    restart: 'no'
    build: .
    volumes:
      - ./configs:/opt/federation-lab/configs
      - ./output:/opt/federation-lab/output
      - ./default_models:/opt/federation-lab/default_models
    command: python3 -m fltk single configs/local_experiment.yaml --rank=0
    environment:
    - PYTHONUNBUFFERED=1
    - RANK=0
    - WORLD_SIZE=2
    - GLOO_SOCKET_IFNAME=eth0
    - TP_SOCKET_IFNAME=eth0
    ports:
    - 5000:5000
    networks:
      local_network_dev:
        ipv4_address: 10.5.0.2
  client_slow_1:
    restart: 'no'
    build: .
    command: python3 -m fltk single configs/local_experiment.yaml --rank=1
    volumes:
    - ./configs:/opt/federation-lab/configs
#    - ./docker_data:/opt/federation-lab/data
    - ./default_models:/opt/federation-lab/default_models
#    - ./data_loaders:/opt/federation-lab/data_loaders
    environment:
    - PYTHONUNBUFFERED=1
    - RANK=1
    - WORLD_SIZE=2
    - GLOO_SOCKET_IFNAME=eth0
    - TP_SOCKET_IFNAME=eth0
    depends_on:
    - fl_server
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M

  client_slow_2:
    restart: 'no'
    build: .
    command: python3 -m fltk single configs/local_experiment.yaml --rank=2
    volumes:
      - ./configs:/opt/federation-lab/configs
      #    - ./docker_data:/opt/federation-lab/data
      - ./default_models:/opt/federation-lab/default_models
    #    - ./data_loaders:/opt/federation-lab/data_loaders
    environment:
      - PYTHONUNBUFFERED=1
      - RANK=1
      - WORLD_SIZE=2
      - GLOO_SOCKET_IFNAME=eth0
      - TP_SOCKET_IFNAME=eth0
    depends_on:
      - fl_server
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
networks:
  local_network_dev:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16


