apiVersion: v1
kind: Pod
metadata:
  labels:
    fltk.service: fl-server
  name: fl-server
spec:
  containers:
    - args:
        - python3
        - -m
        - fltk
        - cluster
        - configs/example_cloud_experiment.json
        - --rank=0
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
      image: {{ .Values.provider.domain }}/{{ .Values.provider.projectName }}/{{ .Values.provider.imageName}}
      name: federation-lab-server
      ports:
        - containerPort: {{ (.Values.fltk.port) }}
      resources:
        limits:
          cpu: {{ (.Values.federator.cpu | int) }}
          memory: {{ (.Values.federator.memory | int) }}
      volumeMounts:
        - mountPath: /opt/federation-lab/output
          name: fl-server-claim
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: fl-server-claim
      persistentVolumeClaim:
        claimName: fl-server-claim
status: {}
