federator:
  stub-name: system_stub.yml
  pin-cores: true
  num-cores: 1
clients:
  fast:
    stub-name: stub_default.yml
    amount: 2
    pin-cores: true
    num-cores: 1
    cpu-speed: 1
    cpu-variation: 0
  slow:
    stub-name: stub_default.yml
    amount: 0
    pin-cores: true
    num-cores: 1
    cpu-speed: 1
    cpu-variation: 0
