client_name: # name can be anything
    cpuset: {cpu_set}
    restart: "no" # if it crashes for example
    build: . # look for the docker file where this file is currently located
    volumes:
#      - ./docker_data:/opt/federation-lab/data
      - ./data:/opt/federation-lab/data
      - ./default_models:/opt/federation-lab/default_models
      - ./data_loaders:/opt/federation-lab/data_loaders
      - ./fltk:/opt/federation-lab/fltk
    environment:
      - PYTHONUNBUFFERED=1
      - RANK={rank}
      - WORLD_SIZE={world_size}
      - EXP_CONFIG=${EXP_CONFIG_FILE}
      - MASTER_HOSTNAME=10.5.0.11
      - NIC=eth0
    ports:
      - "5002:5000" # {machine-port}:{docker-port}
    depends_on:
      - "fl_server"
    deploy:
      resources:
        limits:
          cpus: {num_cpus}
