apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f ../docker-compose-gcloud.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fl-server
  name: fl-server
spec:
  containers:
    - env:
        - name: GLOO_SOCKET_IFNAME
          value: eth0
        - name: MASTER_PORT
          value: "5000"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: RANK
          value: "0"
        - name: TP_SOCKET_IFNAME
          value: eth0
        - name: WORLD_SIZE
          value: {{ (.Values.fltk.worldsize | int) }}
      image: gcr.io/cs4290-dml/fltk:latest
      name: federation-lab-server
      ports:
        - containerPort: 5000
      resources: {}
      volumeMounts:
        - mountPath: /opt/federation-lab/output
          name: fl-server-claim
  restartPolicy: Never
  volumes:
    - name: fl-server-claim
      persistentVolumeClaim:
        claimName: fl-server-claim
status: {}
