---
# Experiment configuration
total_epochs: 50
epochs_per_cycle: 1
wait_for_clients: true
net: Cifar10CNN
dataset: cifar10
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'p11_freezoff_iid_tifl_adaptive'
offload_stategy: tifl-adaptive
profiling_time: 30
deadline: 50000
warmup_round: false
output_location: 'output/p11'
tensor_board_active: true
clients_per_round: 3
node_groups:
  slow: [1, 6]
  medium: [7, 12]
  fast: [13, 18]
sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
#sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
sampler_args:
  - 0.07     # label limit || q probability || alpha || unused
  - 42    # random seed || random seed || random seed || unused
system:
  federator:
    # hostname: '131.180.203.94'
    hostname: '10.5.0.11'
    nic: 'eth0'
    # nic: 'enp3s0'
  clients:
    amount: 18
