apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.fltk.service: fl-server-claim
  name: fl-server-claim
spec:
  # Only the Orchestator pod should be able to write to the part. Extractor functions as a simple 'read' to
  # Make datacollection easier.
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.extractor.logging.size }}
  storageClassName: "nfs"
