---
# Experiment configuration
total_epochs: 50
epochs_per_cycle: 1
wait_for_clients: true
net: FashionMNISTCNN
dataset: fashion-mnist
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'p15_freezoff_non_iid_fednova'
offload_stategy: vanilla
optimizer: FedNova
profiling_time: 30
deadline: 50000
warmup_round: false
output_location: 'output/p15'
tensor_board_active: true
clients_per_round: 6
node_groups:
  slow: [1, 2]
  medium: [3, 4]
  fast: [5, 6]
sampler: "n labels" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
#sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
sampler_args:
  - 2     # label limit || q probability || alpha || unused
  - 42    # random seed || random seed || random seed || unused
system:
  federator:
    # hostname: '131.180.203.94'
    hostname: '10.5.0.11'
    nic: 'eth0'
    # nic: 'enp3s0'
  clients:
    amount: 18
