---
# Experiment configuration
total_epochs: 5
epochs_per_cycle: 1
wait_for_clients: true
net: FashionMNISTCNN
dataset: fashion-mnist
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'exp_dev_p2_fedavg'
offload_stategy: vanilla
profiling_time: 100
deadline: 500
warmup_round: false
output_location: 'output/dev_p2'
tensor_board_active: true
clients_per_round: 2
node_groups:
  slow: [1, 1]
  medium: [2, 2]
  fast: [3, 3]
sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
#sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
sampler_args:
  - 0.07     # label limit || q probability || alpha || unused
  - 42    # random seed || random seed || random seed || unused
system:
  federator:
    # hostname: '131.180.203.94'
    hostname: '10.5.0.11'
    nic: 'eth0'
    # nic: 'enp3s0'
  clients:
    amount: 2
