# Individual configuration
offload_stategy: vanilla
deadline: 500000
sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default) || "n labels"
sampler_args:
  - 10     # label limit || q probability || alpha || unused
  - 42    # random seed || random seed || random seed || unused