cluster:
  orchestrator:
    wait_for_clients: true
    # Use the SERVICE provided by the fl-server to connect
    service: 'fl-server.test.svc.cluster.local'
    # Default NIC is eth0
    nic: 'eth0'
  worker:
    prefix: 'client'
execution_config:
  experiment_prefix: 'cloud_experiment'
  tensor_board_active: true
  cuda: false
  net:
    save_model: false
    save_temp_model: false
    save_epoch_interval: 1
    save_model_path: "models"
    epoch_save_start_suffix: "start"
    epoch_save_end_suffix: "end"
  reproducability:
    torch_seed: 42
    arrival_seed: 123
