---
# Experiment configuration
# Experiment configuration
total_epochs: 5
epochs_per_cycle: 1
wait_for_clients: true
net: FashionMNISTCNN
dataset: fashion-mnist
sampler: "uniform"
sampler_args:
  - 0.5     # p degree
  - 42      # random seed
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'experiment_single_machine'
output_location: 'output'
tensor_board_active: true
clients_per_round: 20
system:
  federator:
    # Use the SERVICE provided by the fl-server to connect
    hostname: 'fl-server.default.svc.cluster.local'
    # Default NIC is eth0
    nic: 'eth0'
  clients:
    amount: 20
# For a simple config is provided in configs/poison.example.yaml
poison:
  seed: 420
  ratio: 0.2
  attack:
    type: "flip"
    config:
      - 4: 6
      - 6: 4

