---
# Experiment configuration
total_epochs: 5
epochs_per_cycle: 1
# Use cuda is available; setting to false will force CPU
cuda: true
experiment_prefix: 'experiment_sample'
output_location: 'output'
tensor_board_active: true
system:
  federator:
    hostname: '10.5.0.2'
    nic: 'eth0'
  clients:
    amount: 1
