---
# Experiment configuration
total_epochs: 20
epochs_per_cycle: 1
wait_for_clients: true
net: FashionMNISTCNN
dataset: fashion-mnist
#net: Cifar10CNN
#dataset: cifar10
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'experiment_fmnist_offload'
offload_stategy: offload
profiling_time: 100
deadline: 13
warmup_round: false
output_location: 'output'
tensor_board_active: true
clients_per_round: 4
sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
#sampler: "uniform" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
sampler_args:
  - 0.07     # label limit || q probability || alpha || unused
  - 42    # random seed || random seed || random seed || unused
system:
  federator:
    hostname: '10.5.0.11'
    nic: 'eth0'
  clients:
    amount: 4
