---
# Experiment configuration
total_epochs: 30
epochs_per_cycle: 1
wait_for_clients: true
net: Cifar10CNN
dataset: cifar10
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'experiment_non_iid(dirichlet)'
output_location: 'output'
tensor_board_active: true
clients_per_round: 4
sampler: "dirichlet" # "limit labels" || "q sampler" || "dirichlet" || "uniform" (default)
sampler_args:
  - 0.07     # label limit || q probability || alpha || unused
  - 42    # random seed || random seed || random seed || unused
system:
  federator:
    hostname: '192.168.1.108'
    nic: 'wlp4s0'
  clients:
    amount: 10              # must be multiple of the number of labels for q-sampler and limit-labels
