# For a simple config is provided in configs/poison.example.yaml
poison:
  experiments:
    min_ratio: 0.0
    max_ratio: 0.25
    steps: 2
  attack:
    scenario: "fraction"
    # TODO: timed, early, late
    type: "LABEL_FLIP"
